---
title: record_exception (PythonエージェントAPI)
type: apiDoc
shortDescription: Pythonの例外の詳細をエラーとして記録します。
tags:
  - Agents
  - Python agent
  - Python agent API
metaDescription: 'Python API: This call records the details of a Python exception as an error.'
translationType: machine
---

## 構文

```py
newrelic.agent.record_exception(exc=None, value=None, tb=None, params={}, ignore_errors=[], application=None)
```

このAPIは非推奨になりました。 [`notice_error()`](/docs/agents/python-agent/python-agent-api/notice_error)を使用してください。

## 説明

Pythonの例外の詳細をエラーとして記録します。

デフォルトでは、Pythonエージェントは未処理の例外のみを報告します。 `record_exception`を使用して、Python例外をエラーとして記録します。これは、NewRelicUIで見つけることができます。パラメーターが指定されていない場合は、現在処理されている例外の詳細が使用されます。

[トランザクションごとに最大5つの異なる例外を記録することができます。](/docs/accounts-partnerships/education/getting-started-new-relic/glossary#transaction) また、 [ハーベストサイクルごとにすべてのトランザクションの合計で最大20の例外を記録することができます。](/docs/apm/new-relic-apm/getting-started/glossary#harvest-cycle) 。

監視対象のWeb要求またはバックグラウンドタスクのコンテキスト内で`record_exception()`が呼び出されると、要求またはタスクが報告されているアプリケーションに対して例外の詳細が報告されます。

監視対象のWeb要求またはバックグラウンドタスクのコンテキスト外で呼び出された場合、 [`application`](/docs/agents/python-agent/python-agent-api/application)キーワード引数が指定され、例外が記録されるアプリケーションに対応するアプリケーションオブジェクトが指定されない限り、呼び出しは無視されます。 `newrelic.agent.application()`関数を使用して、適切なアプリケーションオブジェクトを取得できます。

## パラメーター

<Callout variant="tip">
  ほとんどすべての場合、 `record_exception`はパラメータを必要としません。
</Callout>

<table>
  <thead>
    <tr>
      <th width="25%">
        パラメータ
      </th>

      <th>
        説明
      </th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td>
        `exc`

        _クラスオブジェクト_
      </td>

      <td>
        オプションで、めったに使用されません。処理される例外の例外タイプ（クラスオブジェクト）。 [`sys.exc_info()`](https://docs.python.org/2/library/sys.html#sys.exc_info)から返された3つの値（ `exc` 、 `value` 、および`tb` ）のいずれか。これらのパラメータのいずれかを渡す場合は、3つすべてを設定する必要があり、 `None`に設定することはできません。これらの値の1つだけを渡すと、呼び出しは機能しません。
      </td>
    </tr>

    <tr>
      <td>
        `value`

        _整数、文字列、その他_
      </td>

      <td>
        オプションで、めったに使用されません。例外パラメータ。 [`sys.exc_info()`](https://docs.python.org/2/library/sys.html#sys.exc_info)から返された3つの値（ `exc` 、 `value` 、および`tb` ）のいずれか。これらのパラメータのいずれかを渡す場合は、3つすべてを設定する必要があり、 `None`に設定することはできません。これらの値の1つだけを渡すと、呼び出しは機能しません。
      </td>
    </tr>

    <tr>
      <td>
        `tb`

        _物体_
      </td>

      <td>
        オプションで、めったに使用されません。例外が最初に発生したポイントでコールスタックをカプセル化するトレースバックオブジェクト。 [`sys.exc_info()`](https://docs.python.org/2/library/sys.html#sys.exc_info)から返された3つの値（ `exc` 、 `value` 、および`tb` ）のいずれか。これらのパラメータのいずれかを渡す場合は、3つすべてを設定する必要があり、 `None`に設定することはできません。これらの値の1つだけを渡すと、呼び出しは機能しません。
      </td>
    </tr>

    <tr>
      <td>
        `params`

        _ディクト_
      </td>

      <td>
        オプションです。エラーイベントに追加するカスタム属性（トランザクションに既に追加されているカスタム属性に加えて）。 [ハイセキュリティモード](/docs/agents/manage-apm-agents/configuration/high-security-mode) が有効になっている場合、これは機能しません。
      </td>
    </tr>

    <tr>
      <td>
        `ignore_errors`

        _ストリング_
      </td>

      <td>
        オプション。無視するエラーは、 `module:class`の形式で渡すことができます。特定の種類の例外を常に無視し、記録しないようにする必要がある場合に便利です。
      </td>
    </tr>

    <tr>
      <td>
        `application`

        _アプリケーションオブジェクト_
      </td>

      <td>
        オプション。監視対象のWeb要求またはバックグラウンドタスクのコンテキスト外で呼び出された場合、 [`application`オブジェクト](/docs/agents/python-agent/python-agent-api/application)が提供されない限り、呼び出しは無視されます。
      </td>
    </tr>
  </tbody>
</table>

## 戻り値

なし。

## 例

### 例外の報告の簡単な例 [#simple-example]

ほとんどの場合、パラメタを渡す必要はありません。例外を報告したい場合は、次のように呼び出せばよいでしょう。

```py
newrelic.agent.record_exception()
```

### sys.exc_info()タプルと追加パラメータを用いたコール [#complex-example]

`sys.exc_info()`データを使用した`record_exception`の例：

```py
def complex_ignore_errors(exc, val, tb):
   # do some logic here
   return False

newrelic.agent.record_exception(params={'my_special_exception': True}, ignore_errors=complex_ignore_errors)
```

### コールバックの使用例 [#callback-example]

特定の例外タイプの属性に基づいて例外を動的にフィルタリングする必要がある場合は、コールバック関数を指定できます。

```py
def _ignore_errors(exc, value, tb): 
    if instance(value, HTTPError): 
        if value.status == 404: 
            return True

newrelic.agent.record_exception(ignore_errors=_ignore_errors)
```

例外を無視する場合は、callableの戻り値を`True`に設定してください。他のチェックに関係なく例外を無視しない場合は`False`を返し、後続のチェックと組み込みルールで例外を無視するかどうかを決定する必要がある場合は`None`を返します。コールバックは通常、 `True`または`None`のいずれかを返します。