---
title: レコード処理された例外
type: apiDoc
shortDescription: 処理された例外を記録します。オプションで、コンテキストを示す追加の属性を持つマップを取ります。
tags:
  - Mobile monitoring
  - Mobile SDK API
  - Custom instrumentation
metaDescription: Mobile app monitoring API used to analyze handled exceptions and thrown exceptions.
freshnessValidatedDate: '2023-07-20T00:00:00.000Z'
translationType: machine
---

<Tabs>
  <TabsBar>
    <TabsBarItem id="android">
      Android
    </TabsBarItem>

    <TabsBarItem id="ios">
      iOS
    </TabsBarItem>

    <TabsBarItem id="maui">
      .NETマウイ
    </TabsBarItem>

    <TabsBarItem id="unity">
      Unity
    </TabsBarItem>

    <TabsBarItem id="xamarin">
      ザマリン
    </TabsBarItem>
  </TabsBar>

  <TabsPages>
    <TabsPageItem id="android">
      ## 構文 [#syntax]

      ### Java [#java]

      ```java
      NewRelic.recordHandledException(Exception $exceptionToHandle)
      NewRelic.recordHandledException(Exception $exceptionToHandle, Map of String, Object $exceptionAttributes)
      ```

      ```java
      NewRelic.recordHandledException(Throwable $throwableToHandle)
      NewRelic.recordHandledException(Throwable $throwableToHandle, Map of String, Object $exceptionAttributes)
      ```

      ### コトリン [#kotlin]

      ```kotlin
      NewRelic.recordHandledException(
      exception: Exception?,
      exceptionAttributes: Map<String?, Any?>?
      )
      ```

      ```kotlin
      NewRelic.recordHandledException(throwable: Throwable?)
      NewRelic. recordHandledException(
      throwable: Throwable?,
      attributes: Map<String?, Any?>?
      )
      ```

      ## 説明 [#description]

      処理された例外またはその他のスロー可能な型を記録する。オプションで、コンテキストを示す追加属性を持つマップを取ることができます。

      `try{...} catch(){...}`ブロック内で`recordHandledException()`を使用すると、アプリケーションが例外をスローする頻度と状況を把握できます。

      関連するカスタム属性に加えて、イベントには関連する [セッション属性](/docs/insights/insights-data-sources/default-attributes/mobile-default-attributes-insights) があります。イベントデータは、モバイルモニタリングUIの [Crash event trail](/docs/mobile-monitoring/mobile-monitoring-ui/crashes/mobile-crash-event-trail) 、またはNRQL経由で見ることができます。

      ## パラメーター [#parameters]

      <table>
        <thead>
          <tr>
            <th width="30%">
              パラメータ
            </th>

            <th width="30%">
              タイプ
            </th>

            <th>
              説明
            </th>
          </tr>
        </thead>

        <tbody>
          <tr>
            <td>
              `$exceptionToHandle`
            </td>

            <td>
              `Exception`
            </td>

            <td>
              必要。記録される例外。
            </td>
          </tr>

          <tr>
            <td>
              `$exceptionAttributes`
            </td>

            <td>
              `Map of String, Object`
            </td>

            <td>
              オプション。例外に関連付けられる属性のマップ。
            </td>
          </tr>
        </tbody>
      </table>

      ## 戻り値 [#return-values]

      正常に記録された場合は`true`を返し、そうでない場合は`false`を返します。

      ## 例 [#examples]

      以下は、クリック時リスナー内から `ClassCastException` を記録する例です。

      ### Java [#java]

      ```java
      public class MainActivity extends Activity {
        ...
        coolButton.setOnClickListener(new View.OnClickListener() {
                  Map myMap = new HashMap<>();
                  @Override
                  public void onClick(View view) {
                      try {
                          myMap.put("Key", "Value");
                          Integer stringVar = (Integer) myMap.get("Key"); //throws ClassCastException
                      } catch (Exception e) {
                          NewRelic.recordHandledException(e, myMap);
                      }
                  }
              });
        ...
      }
      ```

      ### コトリン [#kotlin]

      ```kotlin

      class MainActivity : AppCompatActivity() {

      ....
          binding.fab.setOnClickListener { view ->
              val myMap = mutableMapOf<String,Any>()
              try {
                  myMap["Key"] = "Value"
                  Snackbar.make(view, "Replace with your own action", Snackbar.LENGTH_LONG)
                      .setAnchorView(R.id.fab)
                      .setAction("Action", null).show()
              }catch (exception:Exception) {
                  NewRelic.recordHandledException(exception,myMap)
              }
          }
      ........
      ```
    </TabsPageItem>

    <TabsPageItem id="ios">
      ## 構文 [#syntax]

      ### 目的-c

      ```objectivec
      recordHandledException:(NSException* __nonnull)exception withAttributes:(NSDictionary* __nullable)attributes;
      ```

      ## 説明 [#description]

      処理された例外を記録します (Objective-c のみ)。オプションで、コンテキストを示す追加属性を含むマップを取得します。

      `recordHandledException` APIはクラッシュ分析に役立ちます。キャプチャされたイベントは、アプリケーションが例外をスローする頻度とその条件を理解するのに役立ちます。関連するカスタム属性に加えて、イベントには関連する[セッション属性](/docs/insights/insights-data-sources/default-attributes/mobile-default-attributes-insights)もあります。

      このAPIは、 `NSException`のインスタンスとオプションの`NSDictionary`属性ディクショナリを取得してから、 `recordHandledException`イベントを作成します。[クラッシュイベントトレイルUI](/docs/mobile-monitoring/mobile-monitoring-ui/crashes/mobile-crash-event-trail)でイベントデータを表示し、NRQLでクエリを実行できます。

      <Callout variant="important">
        この関数は Swift コードでは使用しないでください。Swift コードで処理されたエラーを追跡するには、 [recordError](/docs/mobile-monitoring/new-relic-mobile/mobile-sdk/record-errors/) を使用してください。
      </Callout>

      ## パラメーター [#parameters]

      <table>
        <thead>
          <tr>
            <th width="30%">
              パラメータ
            </th>

            <th width={200}>
              タイプ
            </th>

            <th>
              説明
            </th>
          </tr>
        </thead>

        <tbody>
          <tr>
            <td>
              `exception`
            </td>

            <td>
              `NSException`
            </td>

            <td>
              必要。記録される例外。
            </td>
          </tr>

          <tr>
            <td>
              `attributes​`
            </td>

            <td>
              `NSDictionary`
            </td>

            <td>
              任意です。コンテキストを与える属性の辞書。
            </td>
          </tr>
        </tbody>
      </table>

      ## 戻り値 [#return-values]

      イベントが正常に記録された場合は`true`を返し、そうでない場合は`false`を返します。

      ## 例 [#examples]

      以下に、処理される単純な例外の例を示します。

      ```objectivec
      @try {
             @throw [NSException exceptionWithName:@"versionException"
                                            reason:@"App version no longer supported"
                                          userInfo:nil];
           } @catch (NSException* e) {
             [NewRelic recordHandledException:e];
           }
      ```

      別の例、または辞書を使用して処理された例外を次に示します。

      ```objectivec
      NSException *exception = [NSException exceptionWithName:@"MyException" reason:@"I have my reason" userInfo:nil];

          NSDictionary* dictionary = @{@"int": @1,
                                       @"Test Group" : @"A | B"};

          [NewRelic recordHandledException:exception withAttributes:dictionary];
      ```
    </TabsPageItem>

    <TabsPageItem id="android">
      ## 構文 [#syntax]

      ```csharp
      recordError(error, StackTrace.current, attributes: attributes);
      ```

      ## 説明 [#description]

      致命的ではない例外を手動で記録します。

      ## パラメーター [#parameters]

      <table>
        <thead>
          <tr>
            <th width="30%">
              パラメータ
            </th>

            <th width={200}>
              タイプ
            </th>

            <th>
              説明
            </th>
          </tr>
        </thead>

        <tbody>
          <tr>
            <td>
              `exception`
            </td>

            <td>
              `Exception`
            </td>

            <td>
              必要。記録される例外。
            </td>
          </tr>
        </tbody>
      </table>

      ## 戻り値 [#return-values]

      イベントが正常に記録された場合は`true`を返し、そうでない場合は`false`を返します。

      ## 例 [#example]

      ```dart
      try {
        some_code_that_throws_error();
      } catch (ex) {
      NewrelicMobile.instance
              .recordError(error, StackTrace.current, attributes: attributes);
      }
      ```
    </TabsPageItem>

    <TabsPageItem id="maui">
      ## 構文 [#syntax]

      ```csharp
      RecordException(System.Exception exception) : void;
      ```

      ## 説明 [#description]

      処理された例外を記録します。オプションで、コンテキストを示す追加の属性を持つマップを取ります。

      ## パラメーター [#parameters]

      <table>
        <thead>
          <tr>
            <th width="30%">
              パラメータ
            </th>

            <th width={200}>
              タイプ
            </th>

            <th>
              説明
            </th>
          </tr>
        </thead>

        <tbody>
          <tr>
            <td>
              `exception`
            </td>

            <td>
              `Exception`
            </td>

            <td>
              必要。記録される例外。
            </td>
          </tr>
        </tbody>
      </table>

      ## 戻り値 [#return-values]

      イベントが正常に記録された場合は`true`を返し、そうでない場合は`false`を返します。

      ## 例 [#example]

      ```csharp
          try {
            some_code_that_throws_error();
          } catch (Exception ex) {
            CrossNewRelic.Current.RecordException(ex);
          }
      ```
    </TabsPageItem>

    <TabsPageItem id="unity">
      ## 構文 [#syntax]

      ```csharp
      RecordException(System.Exception exception) : void;
      ```

      ## 説明 [#description]

      処理された例外を手動で記録します。

      ## パラメーター [#parameters]

      <table>
        <thead>
          <tr>
            <th width="30%">
              パラメータ
            </th>

            <th width={200}>
              タイプ
            </th>

            <th>
              説明
            </th>
          </tr>
        </thead>

        <tbody>
          <tr>
            <td>
              `exception`
            </td>

            <td>
              `Exception`
            </td>

            <td>
              必要。記録される例外。
            </td>
          </tr>
        </tbody>
      </table>

      ## 戻り値 [#return-values]

      イベントが正常に記録された場合は`true`を返し、そうでない場合は`false`を返します。

      ## 例 [#example]

      ```csharp
          try {
            some_code_that_throws_error();
          } catch (Exception ex) {
            NewRelicAgent.RecordException(e);
          }
      ```
    </TabsPageItem>

    <TabsPageItem id="xamarin">
      ## 構文 [#syntax]

      ```csharp
      RecordException(System.Exception exception) : void;
      ```

      ## 説明 [#description]

      処理された例外を手動で記録します。

      ## パラメーター [#parameters]

      <table>
        <thead>
          <tr>
            <th width="30%">
              パラメータ
            </th>

            <th width={200}>
              タイプ
            </th>

            <th>
              説明
            </th>
          </tr>
        </thead>

        <tbody>
          <tr>
            <td>
              `exception`
            </td>

            <td>
              `Exception`
            </td>

            <td>
              必要。記録される例外。
            </td>
          </tr>
        </tbody>
      </table>

      ## 戻り値 [#return-values]

      イベントが正常に記録された場合は`true`を返し、そうでない場合は`false`を返します。

      ## 例 [#example]

      ```csharp
          try {
            some_code_that_throws_error();
          } catch (Exception ex) {
            CrossNewRelicClient.Current.RecordException(ex);
          }
      ```
    </TabsPageItem>
  </TabsPages>
</Tabs>
