---
title: set_error_group_callback(Python 에이전트 API)
type: apiDoc
shortDescription: 이 방법을 사용하면 오류 수신함 내의 오류 그룹을 특정 식별자로 설정할 수 있습니다.
tags:
  - Agents
  - Python agent
  - Python agent API
metaDescription: 'Python API: Used for implementing error groups.'
translationType: machine
---

## 통사론 [#syntax]

```py
newrelic.agent.set_error_group_callback(callback_function(exc))
```

이 방법을 사용하면 오류 받은 편지함 내의 오류 그룹을 특정 식별자(또는 "지문")로 설정할 수 있습니다.

## 요구 사항 [#requirements]

Python 에이전트 버전 8.8.0 이상.

## 설명 [#description]

이 엔드포인트는 오류 그룹을 등록하는 데 사용되는 콜백이라는 단일 입력을 받습니다. 이 콜백은 고객이 정의하며 에이전트의 [`notice_error` API를](/docs/agents/python-agent/python-agent-api/noticeerror-python-agent-api)트리거한 예외를 수락해야 합니다. 이 설정을 해제하려면 API를 다시 호출하고 콜백을 `None`로 설정합니다.

## 에 대한 매개변수 `set_error_group_callback` [#parameters-set-error-group-callback]

<table>
  <thead>
    <tr>
      <th width="25%">
        매개변수
      </th>

      <th>
        설명
      </th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td>
        `callback`

        _호출 가능 함수_
      </td>

      <td>
        필수의. 정의하려는 콜백 함수입니다. 설정을 해제하려면 `None` 사용하세요.
      </td>
    </tr>

    <tr>
      <td>
        `application`

        _애플리케이션 인스턴스_
      </td>

      <td>
        선택 과목. 애플리케이션 인스턴스가 제공되지 않으면 함수는 활성화된 애플리케이션 인스턴스를 확인합니다.
      </td>
    </tr>
  </tbody>
</table>

## 고객 정의 콜백 함수의 매개변수 [#parameters-customer-defined-callback-function]

<table>
  <thead>
    <tr>
      <th width="25%">
        매개변수
      </th>

      <th>
        설명
      </th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td>
        `exception`

        _런타임 예외_
      </td>

      <td>
        필수의. 이는 에이전트의 [`notice_error` API를](/docs/agents/python-agent/python-agent-api/noticeerror-python-agent-api)트리거한 런타임 예외입니다.
      </td>
    </tr>
  </tbody>
</table>

## 반환 값 [#return-values]

성공하면 API는 원하는 오류 그룹 이름을 나타내는 문자열을 에이전트 속성으로 추가합니다.

실패하면 API는 `error.group.name` 에이전트 속성으로 추가하지 않습니다.

## 사용 예 [#examples]

### 오류 그룹 콜백 설정 [#error-group-callback-example]

`set_error_group_callback` 사용 예:

```py
def customer_callback(exc):
    if isinstance(exc,ValueError):
        return "group1"


def some_other_function():
    try:
        raise ValueError("Oh no!")
    except Exception:
       newrelic.agent.notice_error()


def example_function(customer_callback):
    try:
        newrelic.agent.set_error_group_callback(customer_callback)
        some_other_function()
    finally:
        newrelic.agent.set_error_group_callback(None)
```