---
subject: Python agent
releaseDate: '2018-07-12'
version: 3.4.0.95
downloadLink: 'https://pypi.python.org/pypi/newrelic'
---

## Notes

This release of the Python agent adds support for Python 3.7 and contains various bug fixes.

The agent can be installed using easy_install/pip/distribute via the [Python Package Index](https://pypi.python.org/pypi/newrelic) or can be downloaded directly from the New Relic [download site](https://download.newrelic.com/python_agent/release).

## New Features

* **Support Python 3.7**

  The New Relic Python Agent now supports Python 3.7.

## Bug Fixes

* **Agent raises a KeyError: 'NEW_RELIC_ADMIN_COMMAND' exception causing a crash**

  Under certain conditions, using the newrelic-admin wrapper script could cause an application to crash shortly after startup with a KeyError exception. The cause of the crash has been addressed.
* **Agent raises an AttributeError on Python 3 when using WSGI overrides with multiple app names**

  When using WSGI environ overrides to specify multiple app names as described in the docs [https://docs.newrelic.com/docs/agents/manage-apm-agents/app-naming/use-m...](https://docs.newrelic.com/docs/agents/manage-apm-agents/app-naming/use-multiple-names-app) the agent will raise an AttributeError. This error has been corrected.
* **Agent raises an AttributeError exception under rare conditions when halting a trace**

  Under certain rare conditions, the agent might raise an exception when trying to trace an external call in a transaction that has been forcibly halted. The cause of the exception has been addressed.
* **Agent raises a RuntimeError exception under particular conditions when using the Tornado r3 instrumentation**

  When attempting to yield many times from a wrapped tornado.gen.coroutine when using Tornado's r3 instrumentation, a RuntimeError due to hitting the maximum recursion limit can occur. The cause of this exception has been patched.
