---
title: set_error_group_callback (Python agent API)
type: apiDoc
shortDescription: This method allows error groups within the errors inbox to be set to a specific identifier.
tags:
  - Agents
  - Python agent
  - Python agent API
metaDescription: 'Python API: Used for implementing error groups.'
redirects:
  - /docs/agents/python-agent/python-agent-api/seterrorgroupcallback-python-agent-api
---

## Syntax [#syntax]

```py
newrelic.agent.set_error_group_callback(callback_function(exc))
```

This method allows error groups within the errors inbox to be set to a specific identifier (or "fingerprint"). 

## Requirements [#requirements]

Python agent version 8.8.0 or higher.

## Description [#description]

This endpoint takes in a single input, a callback, which is used to register error groups. This callback is customer-defined and must accept the exception that triggered the agent's [`notice_error` API](/docs/agents/python-agent/python-agent-api/noticeerror-python-agent-api). To unset this setting, call the API again and set the callback to `None`.

## Parameters for `set_error_group_callback` [#parameters-set-error-group-callback]

<table>
  <thead>
    <tr>
      <th width="25%">
        Parameter
      </th>

      <th>
        Description
      </th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td>
        `callback`

        _callable function_
      </td>

      <td>
        Required. The callback function you want to define. Use `None` to unset.
      </td>
    </tr>
  
    <tr>
      <td>
        `application`

        _Application Instance_
      </td>

      <td>
        Optional. If an application instance is not provided, the function will check for the activated application instance.
      </td>
    </tr>

  </tbody>
</table>

## Parameters for customer defined callback function [#parameters-customer-defined-callback-function]

<table>
  <thead>
    <tr>
      <th width="25%">
        Parameter
      </th>

      <th>
        Description
      </th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td>
        `exception`

        _Runtime exception_
      </td>

      <td>
        Required. This would be the runtime exception that triggered the agent's [`notice_error` API](/docs/agents/python-agent/python-agent-api/noticeerror-python-agent-api).
      </td>
    </tr>

  </tbody>
</table>

## Return values [#return-values]

When successful, the API will add a string representing the desired error group name as an agent attribute.

When unsuccessful, the API will not add `error.group.name` as an agent attribute.

## Example usage [#examples]

### Set error group callback [#error-group-callback-example]

An example of using `set_error_group_callback`:

```py
def customer_callback(exc):
    if isinstance(exc,ValueError):
        return "group1"


def some_other_function():
    try:
        raise ValueError("Oh no!")
    except Exception:
       newrelic.agent.notice_error()


def example_function(customer_callback):
    try:
        newrelic.agent.set_error_group_callback(customer_callback)
        some_other_function()
    finally:
        newrelic.agent.set_error_group_callback(None)
```
